services:
  backend:
    build: ./backend
    container_name: backend_service
    ports:
      - "5001:5000"
    volumes:
      - ./backend/instance:/app/instance
    environment:
      - FLASK_APP=app.py
      - FLASK_RUN_HOST=0.0.0.0
      - AMAP_API_KEY=68778fb7fc7baf898edd94a8fc683768


  frontend:
    build: ./frontend
    ports:
      - "8080:80"
    depends_on:
      - backend
    volumes:
      - ./frontend:/usr/share/nginx/html 